### ISSUE TITLE
Challenges with the migration to the topic-per-event topology

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.Transport.AzureServiceBus#1170]
This discussion topic serves as a reference point to capture challenges with the migration to the topic-per-event topology.  Please share with us the challenges you faced or rough edges you discovered during the migration.

There is also a [discuss group entry](https://discuss.particular.net/t/challenges-with-the-migration-to-the-topic-per-event-topology/4251) you can use should you prefer this avenue.

For cases when specific data or insights of the project needs to be disclosed, feel free to raise a [support request](https://particular.net/support).

### Additional Context

- [Topology documentation
](https://docs.particular.net/transports/azure-service-bus/topology?version=asbs_5)
- [Upgrade guide](https://docs.particular.net/transports/upgrades/asbs-4to5)
- [Migration sample](https://docs.particular.net/samples/azure-service-bus-netstandard/topology-migration/)

### Additional ideas

- If needed, codify a live migration approach similar to https://github.com/Particular/docs.particular.net/pull/6989

**Comment by dvdvorle** [comment]
A challenge we encountered while migrating to the new topology is that we can no longer manage all Azure resources using Terraform. This decouples topic creation from permission management and makes it harder to clean up temporary dev/PR environments.

Previously we created the bundle topic using Terraform, where we also assigned the appriopriate permissions (`Azure Service Bus Data Sender` role) to our endpoint specific managed identities. The NServiceBus installer only managed the subscription rules.

In the new topology, we can't manage the topic permissions via Terraform because we don't have any knowledge about the topic/events there. While the NServiceBus installer can create the event-specific topics, it doesn’t seem to assign the necessary permissions. As a result, our endpoints are currently unable to publish events.

We've explored a few mitigation options:
1. Assign `Azure Service Bus Data Sender` at the servicebus namespace level.
   - This violates the principle of least privilege, especially since we share the namespace with unrelated (non-NServiceBus) topics and queues.
   - It doesn’t address the housekeeping challenges in temporary environments.
2. Manually keep a list of topic events in sync in terraform
   - This is tedious and error-prone.
   - We prefer to decouple infrastructure definitions from application code
3. Create some tooling around NServiceBus to export a list of events we can import in terraform
   - This adds maintenance overhead
   - Ideally, NServiceBus could provide a manifest (e.g., JSON/YAML) describing the required topics/subscriptions/queues. Akin to the compile-time SqlScripts.

None of these are ideal, so this is definitly a 'rough edge' for us.

---

To help visualize our setup, here’s a simplified sketch of our solution:

``` yaml
Endpoints:
- Name: Endpoint-A
  Identity: MI-A
  Events:
  - Event-a
- Name: Endpoint-B
  Identity: MI-B
  Events:
  - Event-b
```
We have a company-wide Azure ServiceBus namespace. Endpoint-A is owned by Team A, Endpoint-B by Team B. Each has its own deployment pipeline. During deployment we run the installers under a more privileged identity (MI-installer-x). At runtime each endpoint has its own least-privilege identity.

**Old topology**
``` yaml
Topics:
- Name: Bundle1 # terraform managed
  Permissions:
  - MI-A: Send # terraform managed
  - MI-B: Send # terraform managed
  - MI-installer-A: Owner # inherited from namespace
  - MI-installer-B: Owner # inherited from namespace
  Subscriptions:
  - Endpoint-A # NServiceBus managed
  - Endpoint-B # NServiceBus managed
- Name: Unrelated-Non-NServiceBus-Topic
  Permissions:
  - MI-Unrelated: Send
-
```

**New topology**
Missing `Send` permissions
``` yaml
Topics:
- Name: Event-a # NServiceBus managed
  Permissions:
  - MI-installer-A: Owner # inherited from namespace
  Subscriptions:
  - Endpoint-B # NServiceBus managed
- Name: Event-b # NServiceBus managed
  Permissions:
  - MI-installer-B: Owner # inherited from namespace
  Subscriptions:
  - Endpoint-A # NServiceBus managed
- Name: Unrelated-Non-NServiceBus-Topic
  Permissions:
  - MI-Unrelated: Send
```
